name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip
        restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-pip
    - run: pip install poetry
    - run: poetry install --no-interaction
    - run: poetry run ruff .
    - run: poetry run black --check .
    - run: poetry run pytest --cov=et_fpm --cov-fail-under=85
